$env:DB_TYPE="postgresdb"
$env:DB_POSTGRESDB_HOST="aws-0-us-west-2.pooler.supabase.com"
$env:DB_POSTGRESDB_PORT="5432"
$env:DB_POSTGRESDB_DATABASE="postgres"
$env:DB_POSTGRESDB_USER="postgres.htabdguydyysolkzdilm"
$env:DB_POSTGRESDB_PASSWORD="*Mm0101mM****"
$env:DB_POSTGRESDB_SCHEMA="n8n"
$env:N8N_ENCRYPTION_KEY="nexus_secret_key"

Write-Host "Iniciando importacion remota de n8n a Supabase..."
npx -y n8n@latest import:workflow --input="n8n_templates\WhatsApp_AI_Responder.json"
npx -y n8n@latest import:workflow --input="n8n_templates\AI_agent_chat.json"
npx -y n8n@latest import:workflow --input="n8n_templates\AI_Hybrid_Handler.json"
npx -y n8n@latest import:workflow --input="n8n_templates\YouTube_Summarizer.json"
npx -y n8n@latest import:workflow --input="n8n_templates\AI_agent_scraper.json"
Write-Host "Importacion terminada."
